allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true

# 原 .npmrc 迁移过来的配置（注意改为小驼峰）
shamefullyHoist: true
strictPeerDependencies: false
shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - nanoid@3.3.14

packages: []

catalogs:
  build:
    '@nuxt/devtools': ^3.2.4
    '@nuxt/eslint': ^1.16.0
    '@nuxt/kit': ^4.4.8
    '@nuxtjs/color-mode': ^4.0.1
    '@pinia/nuxt': ^0.11.3
    '@types/node': ^26.0.0
    '@unocss/eslint-config': ^66.7.2
    '@unocss/nuxt': ^66.7.2
    '@vueuse/nuxt': ^14.3.0
    nuxt: ^4.4.8
    unocss: ^66.7.2
    unplugin: ^3.0.0
    vite: ^8.0.16
  dev:
    '@antfu/eslint-config': ^9.0.0
    eslint: ^10.5.0
    eslint-plugin-format: ^2.0.1
    typescript: ^6.0.3
    vue-tsc: ^3.3.5
  frontend:
    '@vueuse/core': ^14.3.0
    maplibre-gl: ^5.24.0
    pinia: ^3.0.4
    vue: ^3.5.38
  icons:
    '@iconify-json/carbon': ^1.2.23
    '@iconify-json/twemoji': ^1.2.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
