allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true

# 原 .npmrc 迁移过来的配置（注意改为小驼峰）
shamefullyHoist: true
strictPeerDependencies: false
shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1

packages: []

catalogs:
  build:
    '@nuxt/devtools': ^3.2.4
    '@nuxt/eslint': ^1.15.2
    '@nuxt/kit': 4.4.2
    '@nuxtjs/color-mode': ^4.0.0
    '@pinia/nuxt': ^0.11.3
    '@types/node': ^25.7.0
    '@unocss/eslint-config': ^66.6.8
    '@unocss/nuxt': ^66.6.8
    '@vueuse/nuxt': ^14.3.0
    nuxt: 4.4.2
    unocss: ^66.6.8
    unplugin: ^3.0.0
    vite: ^8.0.12
  dev:
    '@antfu/eslint-config': ^9.0.0
    eslint: ^10.3.0
    eslint-plugin-format: ^2.0.1
    typescript: ^6.0.3
    vue-tsc: ^3.2.8
  frontend:
    '@vueuse/core': ^14.3.0
    maplibre-gl: ^5.24.0
    pinia: ^3.0.4
    vue: ^3.5.34
  icons:
    '@iconify-json/carbon': ^1.2.21
    '@iconify-json/twemoji': ^1.2.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
